# Generated by Django 3.2 on 2021-05-27 01:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moodtracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('mood', models.CharField(choices=[('Terrible', 'Terrible'), ('Bad', 'Bad'), ('Average', 'Average'), ('Good', 'Good'), ('Amazing', 'Amazing')], max_length=10)),
                ('activities', multiselectfield.db.fields.MultiSelectField(choices=[('School', 'School'), ('Work', 'Work'), ('Exercise', 'Exercise'), ('Friends/Family', 'Friends/Family'), ('Shopping', 'Shopping'), ('Reading', 'Reading'), ('TV/Movies', 'TV/Movies'), ('Relax', 'Relax'), ('None', 'None')], max_length=73)),
            ],
        ),
    ]
